-- MySQL Script generated by MySQL Workbench
-- Mon Apr 13 13:21:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mkbdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mkbdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mkbdd` DEFAULT CHARACTER SET utf8 ;
USE `mkbdd` ;

-- -----------------------------------------------------
-- Table `mkbdd`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkbdd`.`article` (
  `id_article` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `user_tel` VARCHAR(15) NOT NULL,
  `quantite` INT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `fk_article_demande1_idx` (`user_tel` ASC),
  CONSTRAINT `fk_article_demande1`
    FOREIGN KEY (`user_tel`)
    REFERENCES `mkbdd`.`demande` (`user_tel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkbdd`.`catalogue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkbdd`.`catalogue` (
  `nom_produit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nom_produit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkbdd`.`demande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkbdd`.`demande` (
  `user_tel` VARCHAR(15) NOT NULL,
  `data` DATETIME(6) NULL,
  PRIMARY KEY (`user_tel`),
  CONSTRAINT `fk_demande_user1`
    FOREIGN KEY (`user_tel`)
    REFERENCES `mkbdd`.`user` (`tel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkbdd`.`quartier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkbdd`.`quartier` (
  `id_quartier` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `id_ville` INT NOT NULL,
  PRIMARY KEY (`id_quartier`),
  INDEX `fk_quartier_ville1_idx` (`id_ville` ASC),
  CONSTRAINT `fk_quartier_ville1`
    FOREIGN KEY (`id_ville`)
    REFERENCES `mkbdd`.`ville` (`id_ville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkbdd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkbdd`.`user` (
  `tel` VARCHAR(15) NOT NULL,
  `mp` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `id_quartier` INT NOT NULL,
  PRIMARY KEY (`tel`),
  INDEX `fk_user_quartier_idx` (`id_quartier` ASC),
  CONSTRAINT `fk_user_quartier`
    FOREIGN KEY (`id_quartier`)
    REFERENCES `mkbdd`.`quartier` (`id_quartier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkbdd`.`user_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkbdd`.`user_has_user` (
  `donneur` VARCHAR(15) NOT NULL,
  `receveur` VARCHAR(15) NOT NULL,
  `date` DATETIME(6) NULL,
  PRIMARY KEY (`donneur`, `receveur`),
  INDEX `fk_user_has_user_user2_idx` (`receveur` ASC),
  INDEX `fk_user_has_user_user1_idx` (`donneur` ASC),
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`donneur`)
    REFERENCES `mkbdd`.`user` (`tel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`receveur`)
    REFERENCES `mkbdd`.`user` (`tel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkbdd`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkbdd`.`ville` (
  `id_ville` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ville`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
